- name: Setup EC2 with Docker
  hosts: web
  become: yes
  gather_facts: yes

  tasks:

    - name: Update system
      raw: sudo yum update -y

    - name: Install Docker
      raw: sudo amazon-linux-extras install docker -y

    - name: Start Docker
      raw: sudo systemctl start docker && sudo systemctl enable docker

    - name: Add ec2-user to docker group
      raw: sudo usermod -aG docker ec2-user
